// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {remote} from '../models';
import {sshtunnel} from '../models';

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ConnectRemote(arg1:string):Promise<remote.State>;

export function Connection():Promise<remote.State>;

export function DisconnectRemote():Promise<void>;

export function DiscoverSSH():Promise<Array<sshtunnel.Discovered>>;

export function HTTPAddr():Promise<string>;

export function InstallUpdate():Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function PickFolder():Promise<string>;

export function RPC(arg1:string,arg2:string):Promise<string>;

export function Token():Promise<string>;

export function UpdateInTerminal():Promise<void>;
