// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ConnectRemote(arg1) {
  return window['go']['main']['App']['ConnectRemote'](arg1);
}

export function Connection() {
  return window['go']['main']['App']['Connection']();
}

export function DisconnectRemote() {
  return window['go']['main']['App']['DisconnectRemote']();
}

export function DiscoverSSH() {
  return window['go']['main']['App']['DiscoverSSH']();
}

export function HTTPAddr() {
  return window['go']['main']['App']['HTTPAddr']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RPC(arg1, arg2) {
  return window['go']['main']['App']['RPC'](arg1, arg2);
}

export function Token() {
  return window['go']['main']['App']['Token']();
}

export function UpdateInTerminal() {
  return window['go']['main']['App']['UpdateInTerminal']();
}
